spring:
  application:
    name: study46
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: "jdbc:mysql://localhost:3306/user_sys"
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 3000
logging:
  level:
    # "[com.snow.study46.controller]": DEBUG
    # "[com.snow.study46.service]": DEBUG
    "[com.snow.study46.repository]": DEBUG
